import type { IssueStatus } from "../../types";

export const STATUS_ORDER: IssueStatus[] = [
  "backlog",
  "classifying",
  "ready_analyze",
  "in_analyze",
  "ready_arch_design",
  "in_arch_design",
  "ready_dev",
  "in_dev",
  "ready_review",
  "in_review",
  "ready_test",
  "in_test",
  "done",
  "blocked",
  "cancelled",
];

export const ALL_STATUSES: IssueStatus[] = [
  "backlog",
  "classifying",
  "ready_analyze",
  "in_analyze",
  "ready_arch_design",
  "in_arch_design",
  "ready_dev",
  "in_dev",
  "ready_review",
  "in_review",
  "ready_test",
  "in_test",
  "done",
  "blocked",
  "cancelled",
];

/** Statuses shown as board columns (excludes cancelled). */
export const BOARD_STATUSES: IssueStatus[] = [
  "backlog",
  "classifying",
  "ready_analyze",
  "in_analyze",
  "ready_arch_design",
  "in_arch_design",
  "ready_dev",
  "in_dev",
  "ready_review",
  "in_review",
  "ready_test",
  "in_test",
  "done",
  "blocked",
];

export const STATUS_CONFIG: Record<
  IssueStatus,
  {
    label: string;
    iconColor: string;
    hoverBg: string;
    dividerColor: string;
    badgeBg: string;
    badgeText: string;
    columnBg: string;
  }
> = {
  backlog: {
    label: "Backlog",
    iconColor: "text-muted-foreground",
    hoverBg: "hover:bg-accent",
    dividerColor: "bg-muted-foreground/40",
    badgeBg: "bg-muted",
    badgeText: "text-muted-foreground",
    columnBg: "bg-muted/40",
  },
  classifying: {
    label: "Classifying",
    iconColor: "text-orange-400",
    hoverBg: "hover:bg-orange-400/10",
    dividerColor: "bg-orange-400",
    badgeBg: "bg-orange-400",
    badgeText: "text-white",
    columnBg: "bg-orange-400/5",
  },
  ready_analyze: {
    label: "Ready Analyze",
    iconColor: "text-yellow-500",
    hoverBg: "hover:bg-yellow-500/10",
    dividerColor: "bg-yellow-500",
    badgeBg: "bg-yellow-500/20",
    badgeText: "text-yellow-700 dark:text-yellow-300",
    columnBg: "bg-yellow-500/5",
  },
  in_analyze: {
    label: "In Analyze",
    iconColor: "text-yellow-600",
    hoverBg: "hover:bg-yellow-600/10",
    dividerColor: "bg-yellow-600",
    badgeBg: "bg-yellow-600",
    badgeText: "text-white",
    columnBg: "bg-yellow-600/5",
  },
  ready_arch_design: {
    label: "Ready Arch Design",
    iconColor: "text-cyan-500",
    hoverBg: "hover:bg-cyan-500/10",
    dividerColor: "bg-cyan-500",
    badgeBg: "bg-cyan-500/20",
    badgeText: "text-cyan-700 dark:text-cyan-300",
    columnBg: "bg-cyan-500/5",
  },
  in_arch_design: {
    label: "In Arch Design",
    iconColor: "text-cyan-600",
    hoverBg: "hover:bg-cyan-600/10",
    dividerColor: "bg-cyan-600",
    badgeBg: "bg-cyan-600",
    badgeText: "text-white",
    columnBg: "bg-cyan-600/5",
  },
  ready_dev: {
    label: "Ready Dev",
    iconColor: "text-blue-400",
    hoverBg: "hover:bg-blue-400/10",
    dividerColor: "bg-blue-400",
    badgeBg: "bg-blue-400/20",
    badgeText: "text-blue-700 dark:text-blue-300",
    columnBg: "bg-blue-400/5",
  },
  in_dev: {
    label: "In Dev",
    iconColor: "text-blue-600",
    hoverBg: "hover:bg-blue-600/10",
    dividerColor: "bg-blue-600",
    badgeBg: "bg-blue-600",
    badgeText: "text-white",
    columnBg: "bg-blue-600/5",
  },
  ready_review: {
    label: "Ready Review",
    iconColor: "text-violet-400",
    hoverBg: "hover:bg-violet-400/10",
    dividerColor: "bg-violet-400",
    badgeBg: "bg-violet-400/20",
    badgeText: "text-violet-700 dark:text-violet-300",
    columnBg: "bg-violet-400/5",
  },
  in_review: {
    label: "In Review",
    iconColor: "text-violet-600",
    hoverBg: "hover:bg-violet-600/10",
    dividerColor: "bg-violet-600",
    badgeBg: "bg-violet-600",
    badgeText: "text-white",
    columnBg: "bg-violet-600/5",
  },
  ready_test: {
    label: "Ready Test",
    iconColor: "text-rose-400",
    hoverBg: "hover:bg-rose-400/10",
    dividerColor: "bg-rose-400",
    badgeBg: "bg-rose-400/20",
    badgeText: "text-rose-700 dark:text-rose-300",
    columnBg: "bg-rose-400/5",
  },
  in_test: {
    label: "In Test",
    iconColor: "text-rose-600",
    hoverBg: "hover:bg-rose-600/10",
    dividerColor: "bg-rose-600",
    badgeBg: "bg-rose-600",
    badgeText: "text-white",
    columnBg: "bg-rose-600/5",
  },
  done: {
    label: "Done",
    iconColor: "text-info",
    hoverBg: "hover:bg-info/10",
    dividerColor: "bg-info",
    badgeBg: "bg-info",
    badgeText: "text-white",
    columnBg: "bg-info/5",
  },
  blocked: {
    label: "Blocked",
    iconColor: "text-destructive",
    hoverBg: "hover:bg-destructive/10",
    dividerColor: "bg-destructive",
    badgeBg: "bg-destructive",
    badgeText: "text-white",
    columnBg: "bg-destructive/5",
  },
  cancelled: {
    label: "Cancelled",
    iconColor: "text-muted-foreground",
    hoverBg: "hover:bg-accent",
    dividerColor: "bg-muted-foreground/40",
    badgeBg: "bg-muted",
    badgeText: "text-muted-foreground",
    columnBg: "bg-muted/40",
  },
};
